### PR TITLE
replace Newtonsoft.Json with System.Text.Json

### PR DESCRIPTION
**Pull request by ElderJames**

### CODE REVIEW

**Comment by rusuly** [comment]
Hello,

Thanks for your contribution.
Originally I wanted to use Utf8JsonWriter for max performance but the problem is that it targets only netstandard 2.1 while  MySqlCdc also supports netstandard 2.0.
I think we need to polish your PR to use #if NETSTANDARD2_1 check

**Comment by ElderJames** [comment]
As it says here https://github.com/dotnet/runtime/issues/31462#issuecomment-552700925 ,netstandard 2.0 is supported.

**Comment by rusuly** [comment]
Wow, I read the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter?view=netcore-3.1&viewFallbackFrom=netcore-3.1%2F#moniker-applies-to) and didn't even try

**Comment by rusuly** [comment]
I will do manual testing later today and publish the change in on the weekend

**Comment by ElderJames** [comment]
Great!

**Pull request merged**
